import { NextSeo } from "next-seo";

export default function Head() {
  return (
    <>
      <NextSeo useAppDir={true} title="Next Shop" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
